import type { Grant } from "./types";

export const KNOWN_GRANTS: Grant[] = [
  // ============================================================
  // FEDERAL PROGRAMS
  // ============================================================
  {
    id: "known_nwsa_trail_partners",
    source: "known",
    sourceId: "nwsa_trail_partners",
    title: "National Forest System Trail Stewardship Partnership Grant (NWSA/USFS)",
    agency: "National Wilderness Stewardship Alliance / USDA Forest Service",
    agencyCode: "USDA-FS",
    description:
      "Joint partnership between NWSA and USFS focused on engaging nonprofit partners and volunteers in trail stewardship projects across National Forest System Trails. Supports non-motorized, equestrian, and hiking trail maintenance. Perfect fit for wilderness trail work with pack stock and hand tools. Must be 501(c)(3).",
    amountMin: 5000,
    amountMax: 30000,
    deadline: null,
    openDate: null,
    url: "https://www.wildernessalliance.org/trail_funding",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_nwsa_wsp",
    source: "known",
    sourceId: "nwsa_wsp",
    title: "Wilderness Stewardship Performance (WSP) Funding – NWSA",
    agency: "National Wilderness Stewardship Alliance",
    agencyCode: "USDA-FS",
    description:
      "Funding for wilderness stewardship projects that contribute to Wilderness Stewardship Performance metrics on National Forest System wilderness areas. Trail maintenance using minimum tool requirements (hand tools, crosscut saws, pack stock) is a core eligible activity.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.wildernessalliance.org/wsp_funding_info",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_grow_wild",
    source: "known",
    sourceId: "grow_wild",
    title: "Grow Wild Grant Program – NWSA",
    agency: "National Wilderness Stewardship Alliance",
    agencyCode: "USDA-FS",
    description:
      "Supports emerging wilderness stewardship organizations building capacity for trail maintenance and wilderness character monitoring. Ideal for newer nonprofits doing hands-on wilderness trail work.",
    amountMin: 2500,
    amountMax: 10000,
    deadline: null,
    openDate: null,
    url: "https://www.wildernessalliance.org/grow_wild",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_nff",
    source: "known",
    sourceId: "nff",
    title: "National Forest Foundation – Matching Awards Program",
    agency: "National Forest Foundation",
    agencyCode: "USDA-FS",
    description:
      "Matching awards for on-the-ground conservation projects on National Forest System lands. Trail maintenance, restoration, and stewardship projects eligible. Leverages volunteer and partner contributions. Focus on community engagement and measurable outcomes.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.nationalforests.org/grant-programs",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "federal",
  },
  {
    id: "known_blm_ccs",
    source: "known",
    sourceId: "blm_ccs",
    title: "BLM Challenge Cost Share Program",
    agency: "Bureau of Land Management",
    agencyCode: "DOI-BLM",
    description:
      "Partnership funding mechanism for nonprofits and volunteers working on BLM-managed public lands. Trail maintenance, restoration, and stewardship projects. Non-motorized wilderness trail work eligible. Requires matching funds or in-kind contributions.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.blm.gov/get-involved/partnerships",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_usfs_ccs",
    source: "known",
    sourceId: "usfs_ccs",
    title: "USFS Challenge Cost-Share Agreements",
    agency: "USDA Forest Service",
    agencyCode: "USDA-FS",
    description:
      "Cooperative agreements between USFS and nonprofit partners for trail work on National Forest land. Challenge cost-share and participating agreements fund trail maintenance, restoration, and signage projects. Nonprofits contribute matching labor (volunteer hours count as match).",
    amountMin: 5000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://www.fs.usda.gov/working-with-us/partnerships",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_orlp",
    source: "known",
    sourceId: "orlp",
    title: "Outdoor Recreation Legacy Partnership (ORLP)",
    agency: "National Park Service",
    agencyCode: "DOI-NPS",
    description:
      "Large-scale grants for outdoor recreation projects in underserved communities. Funded through the Land and Water Conservation Fund. Trail development, restoration, and recreation infrastructure eligible. Competitive national program with significant funding levels.",
    amountMin: 50000,
    amountMax: 5000000,
    deadline: null,
    openDate: null,
    url: "https://www.nps.gov/subjects/lwcf/orlp.htm",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_americorps",
    source: "known",
    sourceId: "americorps",
    title: "AmeriCorps NCCC / Conservation Corps Partnerships",
    agency: "AmeriCorps / Corporation for National and Community Service",
    agencyCode: "CNCS",
    description:
      "Partner with AmeriCorps National Civilian Community Corps or state Conservation Corps programs to receive trained trail crews at no labor cost. Corps members provide 6-10 week trail maintenance seasons. Nonprofits provide project management, tools, and pack stock support. Utah Conservation Corps (UCC) is the local affiliate.",
    amountMin: 0,
    amountMax: 0,
    deadline: null,
    openDate: null,
    url: "https://americorps.gov/serve/americorps/americorps-nccc",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_volunteer_gov",
    source: "known",
    sourceId: "volunteer_gov",
    title: "Volunteer.gov Partnership Agreements (USFS/BLM)",
    agency: "USDA Forest Service / Bureau of Land Management",
    agencyCode: "USDA-FS",
    description:
      "Federal agencies provide partnership agreements and volunteer coordination support for nonprofits doing trail work on public lands. Includes tools, materials, and sometimes stipends for volunteer coordinators. Register your organization on Volunteer.gov to access opportunities.",
    amountMin: 1000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.volunteer.gov/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_usda_rural",
    source: "known",
    sourceId: "usda_rural",
    title: "USDA Rural Development Community Facilities Grant",
    agency: "USDA Rural Development",
    agencyCode: "USDA",
    description:
      "Grants for essential community facilities in rural areas (populations under 20,000). Outdoor recreation facilities including trails and trailheads eligible. Priority given to communities under 5,500. Can fund trail infrastructure, equipment, and signage.",
    amountMin: 10000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_npf",
    source: "known",
    sourceId: "npf",
    title: "National Park Foundation – Stewardship Grants",
    agency: "National Park Foundation",
    agencyCode: "DOI-NPS",
    description:
      "Official charity of the National Park Service. Funds stewardship projects on NPS lands including trail maintenance, restoration, and volunteer engagement. Focus on connecting people to parks and preserving natural resources.",
    amountMin: 5000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://www.nationalparks.org/our-work/grants",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "federal",
  },
  {
    id: "known_fws_partners",
    source: "known",
    sourceId: "fws_partners",
    title: "Fish & Wildlife Service Partners for Fish and Wildlife",
    agency: "U.S. Fish and Wildlife Service",
    agencyCode: "DOI-FWS",
    description:
      "Voluntary partnerships for habitat restoration and conservation on private and public lands. Trail restoration that benefits wildlife habitat is eligible. Emphasis on projects that restore native habitats and improve wildlife corridors.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.fws.gov/program/partners-fish-and-wildlife",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "federal",
  },
  {
    id: "known_flrea",
    source: "known",
    sourceId: "flrea",
    title: "Federal Lands Recreation Enhancement Act (FLREA) Fee Projects",
    agency: "USDA Forest Service / Bureau of Land Management",
    agencyCode: "USDA-FS",
    description:
      "Recreation fee revenue is reinvested into the sites where it is collected. Local ranger districts can direct FLREA funds toward trail maintenance partnerships. Not a traditional grant — work with your local ranger district to propose trail projects funded by recreation fee revenue.",
    amountMin: 5000,
    amountMax: 75000,
    deadline: null,
    openDate: null,
    url: "https://www.fs.usda.gov/managing-land/recreation-heritage-volunteer/recreation-fee-program",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_ahs_alternative",
    source: "known",
    sourceId: "ahs_alternative",
    title: "American Hiking Society – National Trails Fund",
    agency: "American Hiking Society",
    agencyCode: "AHS",
    description:
      "Annual grants for trail maintenance and restoration projects on public lands. Supports building, maintaining, and improving foot trails. Priority given to projects that engage volunteers, promote stewardship, and serve underrepresented communities. Must be 501(c)(3).",
    amountMin: 5000,
    amountMax: 10000,
    deadline: null,
    openDate: null,
    url: "https://americanhiking.org/national-trails-fund/",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },
  {
    id: "known_bcha",
    source: "known",
    sourceId: "bcha",
    title: "Back Country Horsemen of America – Trail Grants",
    agency: "Back Country Horsemen of America",
    agencyCode: "BCHA",
    description:
      "Grants for trail maintenance projects that use pack stock (horses and mules) on public lands. Perfect fit for non-motorized wilderness trail work. BCHA chapters do trail clearing, bridge repair, and wilderness stewardship with pack stock. Partner or affiliate for access to their grant programs and volunteer networks.",
    amountMin: 1000,
    amountMax: 15000,
    deadline: null,
    openDate: null,
    url: "https://www.bcha.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "federal",
  },

  // ============================================================
  // UTAH STATE & LOCAL
  // ============================================================
  {
    id: "known_rtp_utah",
    source: "known",
    sourceId: "rtp_utah",
    title: "Recreational Trails Program (RTP) – Utah",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Federal-aid program providing funding for development, renovation, and maintenance of recreational trails and trailside facilities. Funds non-motorized and motorized trail projects. Administered by Utah DOR with FHWA funding. Requires 20% match. Eligible: government agencies, nonprofits, tribal entities.",
    amountMin: 10000,
    amountMax: 200000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit", "501(c)(3)"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_rri_utah",
    source: "known",
    sourceId: "rri_utah",
    title: "Recreation Restoration Infrastructure Grant (RRI) – Utah",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Addresses the need to restore, repair, and/or replace aging or degraded outdoor recreation infrastructure on public lands in Utah. Trail restoration, signage replacement, and facility improvements eligible.",
    amountMin: 5000,
    amountMax: 250000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_uorg",
    source: "known",
    sourceId: "uorg",
    title: "Utah Outdoor Recreation Grant (UORG)",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Supports outdoor recreation projects including non-motorized trail construction, recreation amenities, water access, and community park development in Utah.",
    amountMin: 10000,
    amountMax: 1000000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_lwcf_utah",
    source: "known",
    sourceId: "lwcf_utah",
    title: "Land and Water Conservation Fund (LWCF) – Utah",
    agency: "Utah Division of Outdoor Recreation / NPS",
    agencyCode: "DOI-NPS",
    description:
      "Federal reimbursement grant for acquisition and development of public outdoor recreation areas. Administered by Utah DOR. 50% match required. Trail projects on public lands eligible.",
    amountMin: 25000,
    amountMax: 500000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/lwcf/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_cwc",
    source: "known",
    sourceId: "cwc",
    title: "Central Wasatch Commission – Short-Term Projects Grant",
    agency: "Central Wasatch Commission",
    agencyCode: "UT-CWC",
    description:
      "Funds recreational stewardship and environmental protection projects in the Central Wasatch Mountains. Trail maintenance, watershed protection, and visitor management eligible. Next call for ideas opens January 13–February 10, 2026.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: "2026-02-10",
    openDate: "2026-01-13",
    url: "https://cwc.utah.gov/projects/",
    status: "upcoming",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "state",
  },
  {
    id: "known_ut_community_impact",
    source: "known",
    sourceId: "ut_community_impact",
    title: "Utah Community Impact Fund",
    agency: "Utah Permanent Community Impact Fund Board",
    agencyCode: "UT-CIB",
    description:
      "Distributes mineral lease and other resource extraction revenue to communities across Utah. Funds public infrastructure including trails, trailheads, and recreation facilities. Available to local governments and their nonprofit partners in impacted communities.",
    amountMin: 10000,
    amountMax: 500000,
    deadline: null,
    openDate: null,
    url: "https://jobs.utah.gov/housing/community/cib/index.html",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_ut_ffsl",
    source: "known",
    sourceId: "ut_ffsl",
    title: "Utah Division of Forestry, Fire, and State Lands – Stewardship",
    agency: "Utah FFSL",
    agencyCode: "UT-FFSL",
    description:
      "Stewardship programs on Utah state trust lands. Trail maintenance, fire prevention, and watershed protection projects eligible. Partner with FFSL for access to state trust land trail projects.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://ffsl.utah.gov/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_slco_zap",
    source: "known",
    sourceId: "slco_zap",
    title: "Salt Lake County ZAP (Zoo Arts & Parks) Tax Grants",
    agency: "Salt Lake County",
    agencyCode: "UT-SLC",
    description:
      "Salt Lake County's 0.1% sales tax dedicated to outdoor recreation, arts, and parks. Funds trail projects, trailhead improvements, and outdoor recreation access within Salt Lake County. Annual grant cycle.",
    amountMin: 5000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://slco.org/zap/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_ut_trails_foundation",
    source: "known",
    sourceId: "ut_trails_foundation",
    title: "Trails Foundation of Northern Utah – Trail Grants",
    agency: "Trails Foundation of Northern Utah",
    agencyCode: "UT-TFNU",
    description:
      "Supports trail development and maintenance in Northern Utah (Weber, Davis, Morgan, Box Elder counties). Non-motorized trail projects eligible. Focus on connecting communities through trail networks.",
    amountMin: 2500,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.tfnu.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },
  {
    id: "known_ut_cpr",
    source: "known",
    sourceId: "ut_cpr",
    title: "Utah Community Parks & Recreation Grant (CPR)",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Funds community parks and recreation projects in Utah. Trailhead facilities, interpretive signage, and recreation infrastructure eligible. Less focus on wilderness but relevant for trailhead and access improvements.",
    amountMin: 5000,
    amountMax: 200000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "state",
  },

  // ============================================================
  // PRIVATE FOUNDATIONS
  // ============================================================
  {
    id: "known_maki",
    source: "known",
    sourceId: "maki",
    title: "Maki Foundation – Environmental Conservation Grants",
    agency: "Maki Foundation",
    agencyCode: "PRIVATE",
    description:
      "Grants for small, community-based nonprofits in the Rocky Mountain West focused on protecting public lands, preserving biodiversity, and environmental conservation. Wilderness protection, river conservation, and public lands management eligible. Awards $1,000–$5,000.",
    amountMin: 1000,
    amountMax: 5000,
    deadline: "2026-04-30",
    openDate: null,
    url: "https://www.makifoundation.org/",
    status: "open",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_eccles_willard",
    source: "known",
    sourceId: "eccles_willard",
    title: "Willard L. Eccles Charitable Foundation",
    agency: "Willard L. Eccles Charitable Foundation",
    agencyCode: "PRIVATE",
    description:
      "Major Utah foundation providing up to $1M to Utah nonprofits. Focus areas include environmental conservation, education, social services, and science. Trail stewardship and public lands conservation projects in Utah are strong candidates.",
    amountMin: 10000,
    amountMax: 1000000,
    deadline: "2026-12-31",
    openDate: null,
    url: "https://www.tgci.com/funding-sources/ut/top",
    status: "open",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_eccles_gs",
    source: "known",
    sourceId: "eccles_gs",
    title: "George S. and Dolores Dore Eccles Foundation",
    agency: "George S. and Dolores Dore Eccles Foundation",
    agencyCode: "PRIVATE",
    description:
      "One of Utah's largest private foundations. Supports environmental conservation, education, and community development in Utah and the Intermountain West. Trail and public lands stewardship projects eligible.",
    amountMin: 10000,
    amountMax: 500000,
    deadline: null,
    openDate: null,
    url: "https://www.ecclesfoundation.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_lawrence",
    source: "known",
    sourceId: "lawrence",
    title: "Lawrence Foundation – Environmental Grants",
    agency: "The Lawrence Foundation",
    agencyCode: "PRIVATE",
    description:
      "Private family foundation supporting environmental causes. Grants typically $5,000–$10,000 for grassroots organizations. Trail conservation, wilderness stewardship, and land protection eligible. Prefers direct-action groups with clear measurable outcomes.",
    amountMin: 5000,
    amountMax: 10000,
    deadline: null,
    openDate: null,
    url: "https://thelawrencefoundation.org/",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_cfu",
    source: "known",
    sourceId: "cfu",
    title: "Community Foundation of Utah – Grants",
    agency: "Community Foundation of Utah",
    agencyCode: "PRIVATE",
    description:
      "Utah's community foundation with multiple grant cycles. Connects donors to nonprofits. Environmental conservation and community development focus areas. Trail stewardship aligns with their community impact goals. Also hosts the Utah Grantmakers Alliance.",
    amountMin: 2500,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://utahcf.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_wyss",
    source: "known",
    sourceId: "wyss",
    title: "Wyss Foundation – Public Lands Conservation",
    agency: "Wyss Foundation",
    agencyCode: "PRIVATE",
    description:
      "Major conservation foundation focused on protecting public lands in the American West. Funds land conservation, wilderness stewardship, and outdoor recreation access. Strong focus on western states including Utah. One of the largest private funders of public lands conservation.",
    amountMin: 25000,
    amountMax: 500000,
    deadline: null,
    openDate: null,
    url: "https://www.wyssfoundation.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "foundation",
  },
  {
    id: "known_wilburforce",
    source: "known",
    sourceId: "wilburforce",
    title: "Wilburforce Foundation – Western Conservation Grants",
    agency: "Wilburforce Foundation",
    agencyCode: "PRIVATE",
    description:
      "Supports conservation organizations in the western US and western Canada. Focus on protecting wildlands, wildlife, and clean water. Trail stewardship that protects wilderness character and wildlife habitat is a good fit. Grants range $15K–$100K.",
    amountMin: 15000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://www.wilburforce.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_bullitt",
    source: "known",
    sourceId: "bullitt",
    title: "Bullitt Foundation – Conservation Grants",
    agency: "Bullitt Foundation",
    agencyCode: "PRIVATE",
    description:
      "Supports conservation organizations in the Pacific Northwest and Intermountain West. Focus on protecting wild lands, rivers, and ecosystems. Trail work that preserves wilderness character in the Intermountain region is eligible.",
    amountMin: 10000,
    amountMax: 75000,
    deadline: null,
    openDate: null,
    url: "https://www.bullitt.org/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_sorenson",
    source: "known",
    sourceId: "sorenson",
    title: "Sorenson Legacy Foundation – Community Impact",
    agency: "Sorenson Legacy Foundation",
    agencyCode: "PRIVATE",
    description:
      "Utah-based foundation supporting education, community development, and environmental sustainability. Outdoor recreation and conservation projects in Utah are eligible. Focus on programs that strengthen Utah communities.",
    amountMin: 5000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://sorensonlegacyfoundation.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_doris_duke",
    source: "known",
    sourceId: "doris_duke",
    title: "Doris Duke Charitable Foundation – Environment Program",
    agency: "Doris Duke Charitable Foundation",
    agencyCode: "PRIVATE",
    description:
      "Major national foundation with an environment program focused on climate change, conservation, and land protection. Supports organizations working to protect wildlife, land, and water. Trail stewardship as a vehicle for conservation is a strong framing.",
    amountMin: 25000,
    amountMax: 500000,
    deadline: null,
    openDate: null,
    url: "https://www.ddcf.org/what-we-fund/environment/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "foundation",
  },
  {
    id: "known_noorda",
    source: "known",
    sourceId: "noorda",
    title: "Ray and Tye Noorda Foundation",
    agency: "Ray and Tye Noorda Foundation",
    agencyCode: "PRIVATE",
    description:
      "One of Utah's top funders. Supports education, community, and quality of life initiatives in Utah. Outdoor recreation and community infrastructure projects in Utah are eligible. Strong interest in programs that improve Utahns' quality of life.",
    amountMin: 10000,
    amountMax: 250000,
    deadline: null,
    openDate: null,
    url: "https://noordafoundation.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "foundation",
  },

  // ============================================================
  // CORPORATE GRANTS
  // ============================================================
  {
    id: "known_patagonia",
    source: "known",
    sourceId: "patagonia",
    title: "Patagonia Environmental Grants",
    agency: "Patagonia",
    agencyCode: "PRIVATE",
    description:
      "Grassroots environmental grants for organizations working to protect and restore the natural environment. Trail conservation, wilderness stewardship, and public lands protection projects eligible. Prefers groups with direct-action agendas.",
    amountMin: 5000,
    amountMax: 20000,
    deadline: null,
    openDate: null,
    url: "https://www.patagonia.com/how-we-fund/",
    status: "recurring",
    eligibility: ["12", "nonprofit", "501(c)(3)"],
    categories: ["ENV"],
    grantType: "corporate",
  },
  {
    id: "known_rei",
    source: "known",
    sourceId: "rei",
    title: "REI Cooperative Action Fund",
    agency: "REI Co-op",
    agencyCode: "PRIVATE",
    description:
      "Supports nonprofit organizations working to increase equitable access to the outdoors and protect outdoor spaces. Trail maintenance, stewardship, and outdoor recreation access projects eligible.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.rei.com/stewardship/creating-access",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "corporate",
  },
  {
    id: "known_conservation_alliance",
    source: "known",
    sourceId: "conservation_alliance",
    title: "The Conservation Alliance – Member Collective Grants",
    agency: "The Conservation Alliance",
    agencyCode: "PRIVATE",
    description:
      "Network of 270+ outdoor companies that pool funding for grassroots conservation. Member companies (including Patagonia, REI, The North Face, KEEN) vote on grants each year. Funds protection of rivers, trails, wild lands, and recreation areas. Highly competitive but significant funding.",
    amountMin: 25000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://conservationalliance.com/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "corporate",
  },
  {
    id: "known_keen",
    source: "known",
    sourceId: "keen",
    title: "KEEN Effect Grants",
    agency: "KEEN Footwear",
    agencyCode: "PRIVATE",
    description:
      "KEEN supports nonprofits promoting responsible outdoor activity. Looking for creative projects with clear goals that introduce new audiences to exploration. Awards $10,000 each, approximately 5 groups per quarterly cycle.",
    amountMin: 10000,
    amountMax: 10000,
    deadline: null,
    openDate: null,
    url: "https://www.keenfootwear.com/keen-effect/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "corporate",
  },
  {
    id: "known_llbean",
    source: "known",
    sourceId: "llbean",
    title: "L.L. Bean Community Grants",
    agency: "L.L. Bean",
    agencyCode: "PRIVATE",
    description:
      "L.L. Bean supports nonprofits that increase access to outdoor recreation, protect natural spaces, and foster healthy lifestyles. Trail maintenance, stewardship, and outdoor education projects eligible. National program.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.llbean.com/llbean/community",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "corporate",
  },
  {
    id: "known_clif",
    source: "known",
    sourceId: "clif",
    title: "Clif Family Foundation – Environmental Grants",
    agency: "Clif Bar Family Foundation",
    agencyCode: "PRIVATE",
    description:
      "Supports grassroots environmental organizations across the US and Canada. Average award ~$6,600, distributed among hundreds of nonprofits. Trail conservation, public lands protection, and environmental stewardship eligible.",
    amountMin: 2000,
    amountMax: 15000,
    deadline: null,
    openDate: null,
    url: "https://clifbarfamilyfoundation.org/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "corporate",
  },
  {
    id: "known_vf_foundation",
    source: "known",
    sourceId: "vf_foundation",
    title: "VF Foundation (The North Face / Timberland)",
    agency: "VF Corporation",
    agencyCode: "PRIVATE",
    description:
      "VF Corporation (parent of The North Face, Timberland, and 12+ brands) grants $8M+ annually for conservation and outdoor access. Focus on environmental sustainability, outdoor recreation access, and community stewardship.",
    amountMin: 10000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://www.vfc.com/sustainability-and-responsibility/community",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
    grantType: "corporate",
  },
  {
    id: "known_yamaha",
    source: "known",
    sourceId: "yamaha",
    title: "Yamaha Outdoor Access Initiative",
    agency: "Yamaha Motor Corporation",
    agencyCode: "PRIVATE",
    description:
      "Supports land stewardship and public land access. Quarterly applications from nonprofit organizations and community groups. Focus on responsible land use, wildlife conservation, and access improvements. Trail maintenance and access projects eligible.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.yamaha-motor.com/outdoor-access-initiative",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "corporate",
  },
  {
    id: "known_black_diamond",
    source: "known",
    sourceId: "black_diamond",
    title: "Black Diamond Equipment – Conservation Grants",
    agency: "Black Diamond Equipment (Salt Lake City, UT)",
    agencyCode: "PRIVATE",
    description:
      "Utah-based outdoor equipment company supporting conservation in the climbing and trail communities. Trail and backcountry access projects eligible. Local connection to the Utah outdoor community is a strong advantage.",
    amountMin: 2500,
    amountMax: 15000,
    deadline: null,
    openDate: null,
    url: "https://www.blackdiamondequipment.com/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "corporate",
  },
  {
    id: "known_osprey",
    source: "known",
    sourceId: "osprey",
    title: "Osprey Packs – Trail Stewardship Support",
    agency: "Osprey Packs",
    agencyCode: "PRIVATE",
    description:
      "Osprey supports wilderness and trail stewardship through donations and partnerships. Focus on protecting wild places and maintaining trail access. Partner with Osprey for equipment donations, funding, and brand co-promotion on trail projects.",
    amountMin: 2500,
    amountMax: 20000,
    deadline: null,
    openDate: null,
    url: "https://www.osprey.com/giving-back",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "corporate",
  },
  {
    id: "known_columbia",
    source: "known",
    sourceId: "columbia",
    title: "Columbia Sportswear – Community Giving",
    agency: "Columbia Sportswear",
    agencyCode: "PRIVATE",
    description:
      "Columbia supports outdoor recreation access and environmental conservation through their community giving program. Trail stewardship, outdoor education, and conservation projects eligible.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.columbia.com/sustainability",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "corporate",
  },
  {
    id: "known_nemo",
    source: "known",
    sourceId: "nemo",
    title: "NEMO Equipment – Conservation Grants",
    agency: "NEMO Equipment",
    agencyCode: "PRIVATE",
    description:
      "NEMO supports backcountry conservation projects. Trail maintenance, wilderness stewardship, and leave-no-trace initiatives eligible. Small grants for grassroots organizations.",
    amountMin: 1000,
    amountMax: 10000,
    deadline: null,
    openDate: null,
    url: "https://www.nemoequipment.com/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["ENV"],
    grantType: "corporate",
  },
  {
    id: "known_nrf",
    source: "known",
    sourceId: "nrf",
    title: "National Recreation Foundation – Outdoor Grants",
    agency: "National Recreation Foundation",
    agencyCode: "PRIVATE",
    description:
      "Funds outdoor recreation projects for youth and underserved communities. Trail projects that engage young people in outdoor stewardship are a strong fit. Annual grant cycle.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.nationalrecreationfoundation.org/our-grants/outdoor-grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
    grantType: "corporate",
  },

  // ============================================================
  // SPONSORSHIP OPPORTUNITIES
  // ============================================================
  {
    id: "known_w3w",
    source: "known",
    sourceId: "w3w",
    title: "what3words – Trail Signage Sponsorship (Pitch Opportunity)",
    agency: "what3words",
    agencyCode: "SPONSOR",
    description:
      "SPONSORSHIP IDEA: Partner with what3words to include w3w addresses on every trail sign installed. Value proposition for w3w: brand exposure on hundreds of wilderness trail signs, real-world use case for emergency location (lost hikers give 911 their w3w address). Value for nonprofit: sponsorship revenue per sign, improved hiker safety, modern navigation on traditional signage. Pitch: 'Every sign we install features a what3words address for emergency location — turning trail signage into a lifesaving navigation tool.'",
    amountMin: 5000,
    amountMax: 100000,
    deadline: null,
    openDate: null,
    url: "https://what3words.com/partners",
    status: "pitch",
    eligibility: ["nonprofit"],
    categories: ["NR"],
    grantType: "sponsorship",
  },
  {
    id: "known_garmin",
    source: "known",
    sourceId: "garmin",
    title: "Garmin – Outdoor Recreation Sponsorship (Pitch Opportunity)",
    agency: "Garmin",
    agencyCode: "SPONSOR",
    description:
      "SPONSORSHIP IDEA: Partner with Garmin for trail mapping data and equipment sponsorship. Garmin devices are the primary navigation tool for wilderness users. Co-brand trail signs with Garmin trail waypoints, provide inReach devices to trail crews for safety, and contribute trail data to Garmin's mapping platform.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.garmin.com/en-US/outdoor-recreation/",
    status: "pitch",
    eligibility: ["nonprofit"],
    categories: ["NR"],
    grantType: "sponsorship",
  },
  {
    id: "known_onx",
    source: "known",
    sourceId: "onx",
    title: "onX – Trail Data Partnership (Pitch Opportunity)",
    agency: "onX (Missoula, MT)",
    agencyCode: "SPONSOR",
    description:
      "SPONSORSHIP IDEA: onX (Hunt, Backcountry, Offroad apps) uses trail and land data. Partner to provide real-time trail condition data from your crews — feed trail status, closures, and conditions directly into onX maps. In return: sponsorship funding, gear, and brand exposure. onX users are exactly your target supporter demographic.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.onxmaps.com/",
    status: "pitch",
    eligibility: ["nonprofit"],
    categories: ["NR"],
    grantType: "sponsorship",
  },
];
