import type { Grant } from "./types";

export const KNOWN_GRANTS: Grant[] = [
  {
    id: "known_rtp_utah",
    source: "known",
    sourceId: "rtp_utah",
    title: "Recreational Trails Program (RTP) – Utah",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Federal-aid program providing funding for development, renovation, and maintenance of recreational trails and trailside facilities. Funds non-motorized and motorized trail projects. Administered by Utah DOR with FHWA funding. Requires 20% match. Eligible: government agencies, nonprofits, tribal entities.",
    amountMin: 10000,
    amountMax: 200000,
    deadline: null, // Varies by cycle
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit", "501(c)(3)"],
    categories: ["NR"],
  },
  {
    id: "known_rri_utah",
    source: "known",
    sourceId: "rri_utah",
    title: "Recreation Restoration Infrastructure Grant (RRI) – Utah",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Addresses the need to restore, repair, and/or replace aging or degraded outdoor recreation infrastructure on public lands in Utah. Trail restoration, signage replacement, and facility improvements eligible.",
    amountMin: 5000,
    amountMax: 250000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
  },
  {
    id: "known_uorg",
    source: "known",
    sourceId: "uorg",
    title: "Utah Outdoor Recreation Grant (UORG)",
    agency: "Utah Division of Outdoor Recreation",
    agencyCode: "UT-DOR",
    description:
      "Supports outdoor recreation projects including non-motorized trail construction, recreation amenities, water access, and community park development in Utah.",
    amountMin: 10000,
    amountMax: 1000000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
  },
  {
    id: "known_lwcf_utah",
    source: "known",
    sourceId: "lwcf_utah",
    title: "Land and Water Conservation Fund (LWCF) – Utah",
    agency: "Utah Division of Outdoor Recreation / NPS",
    agencyCode: "DOI-NPS",
    description:
      "Federal reimbursement grant for acquisition and development of public outdoor recreation areas. Administered by Utah DOR. 50% match required. Trail projects on public lands eligible.",
    amountMin: 25000,
    amountMax: 500000,
    deadline: null,
    openDate: null,
    url: "https://recreation.utah.gov/grants/lwcf/",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
  },
  {
    id: "known_nwsa_trail_partners",
    source: "known",
    sourceId: "nwsa_trail_partners",
    title:
      "National Forest System Trail Stewardship Partnership Grant (NWSA/USFS)",
    agency: "National Wilderness Stewardship Alliance / USDA Forest Service",
    agencyCode: "USDA-FS",
    description:
      "Joint partnership between NWSA and USFS focused on engaging nonprofit partners and volunteers in trail stewardship projects across National Forest System Trails. Supports non-motorized, equestrian, and hiking trail maintenance. Perfect fit for wilderness trail work with pack stock and hand tools. Must be 501(c)(3).",
    amountMin: 5000,
    amountMax: 30000,
    deadline: null,
    openDate: null,
    url: "https://www.wildernessalliance.org/trail_funding",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
  },
  {
    id: "known_nff",
    source: "known",
    sourceId: "nff",
    title: "National Forest Foundation – Matching Awards Program",
    agency: "National Forest Foundation",
    agencyCode: "USDA-FS",
    description:
      "Matching awards for on-the-ground conservation projects on National Forest System lands. Trail maintenance, restoration, and stewardship projects eligible. Leverages volunteer and partner contributions. Focus on community engagement and measurable outcomes.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.nationalforests.org/grant-programs",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
  },
  {
    id: "known_blm_ccs",
    source: "known",
    sourceId: "blm_ccs",
    title: "BLM Challenge Cost Share Program",
    agency: "Bureau of Land Management",
    agencyCode: "DOI-BLM",
    description:
      "Partnership funding mechanism for nonprofits and volunteers working on BLM-managed public lands. Trail maintenance, restoration, and stewardship projects. Non-motorized wilderness trail work eligible. Requires matching funds or in-kind contributions.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.blm.gov/get-involved/partnerships",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR"],
  },
  {
    id: "known_patagonia",
    source: "known",
    sourceId: "patagonia",
    title: "Patagonia Environmental Grants",
    agency: "Patagonia",
    agencyCode: "PRIVATE",
    description:
      "Grassroots environmental grants for organizations working to protect and restore the natural environment. Trail conservation, wilderness stewardship, and public lands protection projects eligible. Prefers groups with direct-action agendas.",
    amountMin: 5000,
    amountMax: 20000,
    deadline: null,
    openDate: null,
    url: "https://www.patagonia.com/how-we-fund/",
    status: "recurring",
    eligibility: ["12", "nonprofit", "501(c)(3)"],
    categories: ["ENV"],
  },
  {
    id: "known_rei",
    source: "known",
    sourceId: "rei",
    title: "REI Cooperative Action Fund",
    agency: "REI Co-op",
    agencyCode: "PRIVATE",
    description:
      "Supports nonprofit organizations working to increase equitable access to the outdoors and protect outdoor spaces. Trail maintenance, stewardship, and outdoor recreation access projects eligible.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: null,
    openDate: null,
    url: "https://www.rei.com/stewardship/creating-access",
    status: "recurring",
    eligibility: ["12", "nonprofit"],
    categories: ["NR", "ENV"],
  },
  {
    id: "known_nwsa_wsp",
    source: "known",
    sourceId: "nwsa_wsp",
    title: "Wilderness Stewardship Performance (WSP) Funding – NWSA",
    agency: "National Wilderness Stewardship Alliance",
    agencyCode: "USDA-FS",
    description:
      "Funding for wilderness stewardship projects that contribute to Wilderness Stewardship Performance metrics on National Forest System wilderness areas. Trail maintenance using minimum tool requirements (hand tools, crosscut saws, pack stock) is a core eligible activity.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    openDate: null,
    url: "https://www.wildernessalliance.org/wsp_funding_info",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
  },
  {
    id: "known_grow_wild",
    source: "known",
    sourceId: "grow_wild",
    title: "Grow Wild Grant Program – NWSA",
    agency: "National Wilderness Stewardship Alliance",
    agencyCode: "USDA-FS",
    description:
      "Supports emerging wilderness stewardship organizations building capacity for trail maintenance and wilderness character monitoring. Ideal for newer nonprofits doing hands-on wilderness trail work.",
    amountMin: 2500,
    amountMax: 10000,
    deadline: null,
    openDate: null,
    url: "https://www.wildernessalliance.org/grow_wild",
    status: "recurring",
    eligibility: ["12", "501(c)(3)", "nonprofit"],
    categories: ["NR"],
  },
];
